export const pokemons = [
  { id:1, nombre:'bulbasaur', tipos:['planta', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', favorito:false },
  { id:2, nombre:'ivysaur', tipos:['planta', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', favorito:false },
  { id:3, nombre:'venusaur', tipos:['planta', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', favorito:false },
  { id:4, nombre:'charmander', tipos:['fuego'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', favorito:false },
  { id:5, nombre:'charmeleon', tipos:['fuego'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png', favorito:false },
  { id:6, nombre:'charizard', tipos:['fuego', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png', favorito:true },
  { id:7, nombre:'squirtle', tipos:['agua'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png', favorito:false },
  { id:8, nombre:'wartortle', tipos:['agua'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png', favorito:false },
  { id:9, nombre:'blastoise', tipos:['agua'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png', favorito:true },
  { id:10, nombre:'caterpie', tipos:['bicho'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png', favorito:false },
  { id:11, nombre:'metapod', tipos:['bicho'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png', favorito:false },
  { id:12, nombre:'butterfree', tipos:['bicho', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png', favorito:true },
  { id:13, nombre:'weedle', tipos:['bicho', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png', favorito:false },
  { id:14, nombre:'kakuna', tipos:['bicho', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png', favorito:false },
  { id:15, nombre:'beedrill', tipos:['bicho', 'veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png', favorito:false },
  { id:16, nombre:'pidgey', tipos:['normal', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png', favorito:false },
  { id:17, nombre:'pidgeotto', tipos:['normal', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png', favorito:false },
  { id:18, nombre:'pidgeot', tipos:['normal', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png', favorito:false },
  { id:19, nombre:'rattata', tipos:['normal'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png', favorito:false },
  { id:20, nombre:'raticate', tipos:['normal'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png', favorito:false },
  { id:21, nombre:'spearow', tipos:['normal', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png', favorito:false },
  { id:22, nombre:'fearow', tipos:['normal', 'volador'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png', favorito:false },
  { id:23, nombre:'ekans', tipos:['veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png', favorito:false },
  { id:24, nombre:'arbok', tipos:['veneno'], sprite:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png', favorito:false }
]
